document.write('<a href="index.html">Strona główna</a>');
document.write('<a href="niezbednik.html">Niezbędnik pasażera</a>');
document.write('<a href="kontakt.html">Kontakt</a>');
document.write('<a href="changelog.html">Historia</a>');
document.write('</header>');
document.write('<div style="width:700px;height:143px;margin:0px auto">');
document.write('<a href="index.html"><img src="zdjecia/mzk1.png" alt="Logo MZK" class="logo" style="float:left"></a>');
document.write('<div class="line-button"><a href="linia_2.html">2</a></div>');
document.write('<div class="line-button"><a href="linia_4.html">4</a></div>');
document.write('<div class="line-button_objazd"><a href="linia_5.html">5</a></div>');
document.write('<div class="line-button"><a href="linia_7.html">7</a></div>');
document.write('<div class="line-button_objazd"><a href="linia_11.html">11</a></div>');