document.write('<a href="index.html">Strona główna</a>');
document.write('<a href="changelog.html">Historia</a>');
document.write('</header>');
document.write('<div>');
document.write('<a href="index.html"><img src="zdjecia/mzk1.png" alt="Logo MZK" class="logo" style="float:left"></a>');
document.write('<div class="wybor_linii">');
document.write('<div class="line-button_miejskie"><a href="linia_2.html">2</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_3.html">3</a></div>');
document.write('<div class="line-button_miejskie objazd"><a href="linia_4.html">4</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_5.html">5</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_8.html">8</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_9.html">9</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_11.html">11</a></div>');
document.write('<div class="line-button_miejskie objazd"><a href="linia_16.html">16</a></div>');
document.write('<div class="line-button_podmiejskie objazd"><a href="linia_29.html">29</a></div>');
document.write('<div class="line-button_pospieszne"><a href="linia_37.html">37</a></div>');
document.write('<div class="line-button_nocne"><a href="linia_40.html">40</a></div>');
document.write('<div class="line-button_nocne"><a href="linia_44.html">44</a></div>');
document.write('</div>');