document.write('<a href="index.html">Strona główna</a>');
document.write('<a href="changelog.html">Historia</a>');
document.write('</header>');
document.write('<div>');
document.write('<a href="index.html"><img src="zdjecia/mzk1.png" alt="Logo MZK" class="logo" style="float:left"></a>');
document.write('<div class="wybor_linii">');
document.write('<div class="line-button_miejskie"><a href="linia_1w.html">1</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_2.html">2</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_4w.html">4</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_6w.html">6</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_8.html">8</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_9.html">9</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_12.html">12</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_13.html">13</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_14w.html">14</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_15.html">15</a></div>');
document.write('<div class="line-button_miejskie"><a href="linia_16w.html">16</a></div>');
document.write('<div class="line-button_podmiejskie"><a href="linia_23.html">23</a></div>');
document.write('<div class="line-button_podmiejskie"><a href="linia_29w.html">29</a></div>');
document.write('<div class="line-button_pospieszne"><a href="linia_37.html">37</a></div>');
document.write('<div class="line-button_pospieszne"><a href="linia_38.html">38</a></div>');
document.write('<div class="line-button_nocne"><a href="linia_40.html">40</a></div>');
document.write('<div class="line-button_nocne"><a href="linia_44.html">44</a></div>');
document.write('<div class="line-button_specjalne"><a href="linia_51w.html">51</a></div>');
document.write('<div class="line-button_specjalne2"><a href="linia_1S.html">1S <img src="zdjecia/koszalek.png"></a></div>');
document.write('</div>');